#########################################################################
#
# Plugin: OriginsCommand
# Author: SpikeyHunter
# Only edit the text in the " ".Do not add commands.
#
#########################################################################

website: "www.towyorigins.com"
discord: "https://discord.gg/EdRdpSH"
towny: "towny"
lobby: "lobby"